# Email noti
telegram_bot_id: "BOT_TOKEN"
telegram_group_id: -1002089748095
telegram_group_thread_id: 667
telegram_sender: "Bot biệt thự"
telegram_receiver: "@phatngluu"
telegram_enable: true
telegram_env: dev # dev stg prod

max_success_timeout: 300
proxy_request_interval: 5

# Proxy configs
proxy_addr: 18.141.12.1:9091 # Dev-SA
# proxy_addr: 35.171.140.196:9091 # Prod-SA
download_urls:
  - https://samsung.com
  - https://facebook.com
  - https://amazon.com
  - https://microsoft.com
  - https://oracle.com
  - https://spacex.com
  - https://foxconn.com
  - https://ibm.com
  - https://hitachi-homeappliances.com
  - https://dell.com
  - https://asus.com
  - https://acer.com
  - https://lenovo.com
  - https://lg.com
proxy_acc:
  - 0xf19eb91b101e9f400893ddfaa57151678612af75511e490a06335c85a9c33f16,Bk3uHdiSIdlk
