version: "3"
services:
  client_bot:
    container_name: client-bot
    image: yadsendewlung/subnet-dpn-client-bot:develop
    build: .
    restart: always
    volumes:
      - /etc:/etc
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
