version: "3"
services:
  client_bot:
    container_name: client-bot
    image: yadsendewlung/subnet-dpn-client-bot:main
    build: .
    restart: always
    volumes:
      - ./config.yaml:/config.yaml
      - /etc:/etc
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
