version: "3"
services:
  client_bot_stg:
    container_name: client-bot-stg
    image: yadsendewlung/subnet-dpn-client-bot:develop
    build: .
    restart: always
    volumes:
      - ./config_stg.yaml:/config.yaml
      - /etc:/etc
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
  # client_bot_dev:
  #   container_name: client-bot-dev
  #   image: yadsendewlung/subnet-dpn-client-bot:develop
  #   build: .
  #   restart: always
  #   volumes:
  #     - ./config_dev.yaml:/config.yaml
  #     - /etc:/etc
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "2048m"
